const products = [
  {
    id: 1,
    name: "لپ‌تاپ ASUS VivoBook 15",
    price: 45900000,
    oldPrice: 48900000,
    discount: 6,
    category: "لپ‌تاپ",
    brand: "ASUS",
    image: "/images/products/asus-vivobook.jpg",
    description:
      "لپ‌تاپ 15.6 اینچی ایسوس با پردازنده قدرتمند، مناسب برای کارهای روزمره، برنامه‌نویسی و استفاده حرفه‌ای.",
    shortDescription: "لپ‌تاپ 15.6 اینچی مناسب برنامه‌نویسی و کارهای روزمره",
    rating: 4.5,
    reviewCount: 128,
    stock: 12,
    isNew: true,
    isFeatured: true,
    tags: ["لپ‌تاپ", "برنامه‌نویسی", "ایسوس"],
  },

  {
    id: 2,
    name: "Apple iPhone 15",
    price: 67900000,
    oldPrice: 72000000,
    discount: 6,
    category: "موبایل",
    brand: "Apple",
    image: "/images/products/iphone-15.jpg",
    description:
      "آیفون 15 با طراحی زیبا، دوربین قدرتمند و عملکرد سریع برای استفاده روزمره و حرفه‌ای.",
    shortDescription: "آیفون 15 با دوربین قدرتمند و عملکرد سریع",
    rating: 4.8,
    reviewCount: 245,
    stock: 8,
    isNew: false,
    isFeatured: true,
    tags: ["موبایل", "آیفون", "اپل"],
  },

  {
    id: 3,
    name: "Samsung Galaxy S24",
    price: 58900000,
    oldPrice: 62500000,
    discount: 6,
    category: "موبایل",
    brand: "Samsung",
    image: "/images/products/galaxy-s24.jpg",
    description:
      "گوشی پرچمدار سامسونگ با نمایشگر باکیفیت، دوربین حرفه‌ای و پردازنده قدرتمند.",
    shortDescription: "پرچمدار سامسونگ با نمایشگر و دوربین حرفه‌ای",
    rating: 4.7,
    reviewCount: 189,
    stock: 15,
    isNew: true,
    isFeatured: true,
    tags: ["موبایل", "سامسونگ", "پرچمدار"],
  },

  {
    id: 4,
    name: "هدفون Sony WH-1000XM5",
    price: 14900000,
    oldPrice: 16500000,
    discount: 10,
    category: "هدفون",
    brand: "Sony",
    image: "/images/products/sony-xm5.jpg",
    description:
      "هدفون بی‌سیم سونی با قابلیت حذف نویز فعال، کیفیت صدای عالی و باتری قدرتمند.",
    shortDescription: "هدفون بی‌سیم حرفه‌ای با حذف نویز فعال",
    rating: 4.9,
    reviewCount: 96,
    stock: 20,
    isNew: false,
    isFeatured: true,
    tags: ["هدفون", "بی‌سیم", "سونی"],
  },

  {
    id: 5,
    name: "Apple Watch Series 9",
    price: 21900000,
    oldPrice: null,
    discount: 0,
    category: "ساعت هوشمند",
    brand: "Apple",
    image: "/images/products/apple-watch-9.jpg",
    description:
      "ساعت هوشمند اپل با امکانات ورزشی، پایش فعالیت‌های روزانه و اتصال سریع به آیفون.",
    shortDescription: "ساعت هوشمند اپل برای ورزش و استفاده روزمره",
    rating: 4.6,
    reviewCount: 74,
    stock: 7,
    isNew: true,
    isFeatured: false,
    tags: ["ساعت", "اپل", "هوشمند"],
  },

  {
    id: 6,
    name: "کیبورد مکانیکی Logitech G Pro",
    price: 6900000,
    oldPrice: 7500000,
    discount: 8,
    category: "لوازم جانبی",
    brand: "Logitech",
    image: "/images/products/logitech-keyboard.jpg",
    description:
      "کیبورد مکانیکی حرفه‌ای لاجیتک با نورپردازی RGB و طراحی مناسب برای گیمینگ و برنامه‌نویسی.",
    shortDescription: "کیبورد مکانیکی RGB مناسب گیمینگ و برنامه‌نویسی",
    rating: 4.4,
    reviewCount: 51,
    stock: 0,
    isNew: false,
    isFeatured: false,
    tags: ["کیبورد", "گیمینگ", "لاجیتک"],
  },

  {
    id: 7,
    name: "ماوس Logitech MX Master 3S",
    price: 6200000,
    oldPrice: null,
    discount: 0,
    category: "لوازم جانبی",
    brand: "Logitech",
    image: "/images/products/mx-master-3s.jpg",
    description:
      "ماوس حرفه‌ای و ارگونومیک لاجیتک با دقت بالا و مناسب برای برنامه‌نویسی و کارهای طولانی.",
    shortDescription: "ماوس حرفه‌ای و ارگونومیک برای کار طولانی",
    rating: 4.8,
    reviewCount: 112,
    stock: 25,
    isNew: false,
    isFeatured: true,
    tags: ["ماوس", "لاجیتک", "برنامه‌نویسی"],
  },

  {
    id: 8,
    name: "مانیتور LG UltraGear 27",
    price: 18900000,
    oldPrice: 20500000,
    discount: 8,
    category: "مانیتور",
    brand: "LG",
    image: "/images/products/lg-ultragear.jpg",
    description:
      "مانیتور 27 اینچی LG با نرخ تازه‌سازی بالا و کیفیت تصویر مناسب برای گیمینگ و کار حرفه‌ای.",
    shortDescription: "مانیتور 27 اینچی با نرخ تازه‌سازی بالا",
    rating: 4.5,
    reviewCount: 63,
    stock: 9,
    isNew: true,
    isFeatured: true,
    tags: ["مانیتور", "LG", "گیمینگ"],
  },
];